#if !UNITY_DOTSPLAYER
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// Generated by ForEachDelegateMemoryTests.tt

using NUnit.Framework;

/*
The purpose of these tests is to validate and make invariant assumptions about
compiler codegen. ForEach needs to receive a delegate, and there are many ways
to implicitly construct one, which are tested below. What we want is to ensure
that we understand the scenarios that generate garbage every frame so we can
detect and warn about them in user code, or replace with our own codegen.

There are two paths to garbage:

1.  ForEach needs to receive a delegate to do its work, which is represented in
    the runtime as a MulticastDelegate. This needs to be allocated from the
    gc, and it is not done statically, but on-demand.

    The result of this `newobj` may always be cached manually, and sometimes is
    cached automatically. That's one of the things the below tests validate.

2.  In a closure, something needs to associate all captured non-global
    variables (including `this`) with the delegate, typically a codegen'd class
    with captures as members. This will involve a gc alloc per-call.

    Note that local functions use a struct for their captures when called in
    the containing method, but this optimization does not apply if the local is
    converted to a delegate.

Categories: (each has a fixture)

    Lambda: Using the () => {} syntax. Current C# compilers (at least Mono and
    Roslyn) will

    This is the key scenario we care about,
    because it's the most natural to use with ForEach. (The other scenarios we
    include because users may adopt them as workarounds.)

    LocalFunction: Using a local function defined in the same function where the
    ForEach is called.

    (Static)Method: An ordinary (static) class method. Aside from lack of access
    to locals (and `this` for statics), these should behave identically to local
    functions.

    "Cached": Because the compilers don't currently cache delegates auto-created
    for anything except lambdas, we'll generate garbage every frame for all
    operations. So we manually cache in order to test just the closure alloc
    behavior.

Tests: (some combos that are impossible are left out)

    Empty: just an empty code block

    WithLocal: a closure that captures a local

    WithThis: a closure that captures `this`

    WithStatic: a method that uses a static
*/

namespace Unity.Entities.Tests.ForEach
{
    class ForEachLambdaMemoryTests : ForEachMemoryTestFixtureBase
    {
        int InvokeEmpty()
        {
            TestInvoke(v => { });
            return 0;
        }

        [Test]
        public void Empty_ShouldAllocFirstCallOnly()
        {
            AllocRecorder.enabled = true;
            var firstCallTotal = InvokeEmpty();
            AllocRecorder.enabled = false;
            var firstCallAllocCount = AllocRecorder.sampleBlockCount;

            AllocRecorder.enabled = true;
            var loopedCallTotal = 0;
            for (var i = 0; i < 5; ++i)
                loopedCallTotal = InvokeEmpty();
            AllocRecorder.enabled = false;
            var loopedCallAllocCount = AllocRecorder.sampleBlockCount;

            Assert.Greater(firstCallAllocCount, 0);
            Assert.Zero(loopedCallAllocCount);

            Assert.AreEqual(0, firstCallTotal);
            Assert.AreEqual(0, loopedCallTotal);
        }

        int InvokeWithLocal()
        {
            int local = 2;
            TestInvoke(v => { local += v; });
            return local;
        }

        [Test]
        public void WithLocal_ShouldAllocEveryCall()
        {
            AllocRecorder.enabled = true;
            var firstCallTotal = InvokeWithLocal();
            AllocRecorder.enabled = false;
            var firstCallAllocCount = AllocRecorder.sampleBlockCount;

            AllocRecorder.enabled = true;
            var loopedCallTotal = 0;
            for (var i = 0; i < 5; ++i)
                loopedCallTotal += InvokeWithLocal();
            AllocRecorder.enabled = false;
            var loopedCallAllocCount = AllocRecorder.sampleBlockCount;

            Assert.Greater(firstCallAllocCount, 0);
            Assert.AreEqual(firstCallAllocCount * 5, loopedCallAllocCount);

            Assert.AreEqual(4, firstCallTotal);
            Assert.AreEqual(20, loopedCallTotal);
        }

        int InvokeWithThis()
        {
            TestInvoke(v => { m_Field += v; });
            return m_Field;
        }

        [Test]
        public void WithThis_ShouldAllocEveryCall()
        {
            AllocRecorder.enabled = true;
            var firstCallTotal = InvokeWithThis();
            AllocRecorder.enabled = false;
            var firstCallAllocCount = AllocRecorder.sampleBlockCount;

            AllocRecorder.enabled = true;
            var loopedCallTotal = 0;
            for (var i = 0; i < 5; ++i)
                loopedCallTotal = InvokeWithThis();
            AllocRecorder.enabled = false;
            var loopedCallAllocCount = AllocRecorder.sampleBlockCount;

            Assert.Greater(firstCallAllocCount, 0);
            Assert.AreEqual(firstCallAllocCount * 5, loopedCallAllocCount);

            Assert.AreEqual(5, firstCallTotal);
            Assert.AreEqual(15, loopedCallTotal);
        }

        int InvokeWithStatic()
        {
            TestInvoke(v => { s_Static += v; });
            return s_Static;
        }

        [Test]
        public void WithStatic_ShouldAllocFirstCallOnly()
        {
            AllocRecorder.enabled = true;
            var firstCallTotal = InvokeWithStatic();
            AllocRecorder.enabled = false;
            var firstCallAllocCount = AllocRecorder.sampleBlockCount;

            AllocRecorder.enabled = true;
            var loopedCallTotal = 0;
            for (var i = 0; i < 5; ++i)
                loopedCallTotal = InvokeWithStatic();
            AllocRecorder.enabled = false;
            var loopedCallAllocCount = AllocRecorder.sampleBlockCount;

            Assert.Greater(firstCallAllocCount, 0);
            Assert.Zero(loopedCallAllocCount);

            Assert.AreEqual(6, firstCallTotal);
            Assert.AreEqual(16, loopedCallTotal);
        }

    }

    class ForEachLocalFunctionMemoryTests : ForEachMemoryTestFixtureBase
    {
        int InvokeEmpty()
        {
            void Empty(int v) { }
            TestInvoke(Empty);
            return 0;
        }

        [Test]
        [Ignore("Unstable")]
        public void Empty_ShouldAllocFirstCallOnly()
        {
            AllocRecorder.enabled = true;
            var firstCallTotal = InvokeEmpty();
            AllocRecorder.enabled = false;
            var firstCallAllocCount = AllocRecorder.sampleBlockCount;

            AllocRecorder.enabled = true;
            var loopedCallTotal = 0;
            for (var i = 0; i < 5; ++i)
                loopedCallTotal = InvokeEmpty();
            AllocRecorder.enabled = false;
            var loopedCallAllocCount = AllocRecorder.sampleBlockCount;

            Assert.Greater(firstCallAllocCount, 0);
            Assert.Zero(loopedCallAllocCount);

            Assert.AreEqual(0, firstCallTotal);
            Assert.AreEqual(0, loopedCallTotal);
        }

        int InvokeWithLocal()
        {
            int local = 2;
            void WithLocal(int v) { local += v; }
            TestInvoke(WithLocal);
            return local;
        }

        [Test]
        [Ignore("Unstable")]
        public void WithLocal_ShouldAllocEveryCall()
        {
            AllocRecorder.enabled = true;
            var firstCallTotal = InvokeWithLocal();
            AllocRecorder.enabled = false;
            var firstCallAllocCount = AllocRecorder.sampleBlockCount;

            AllocRecorder.enabled = true;
            var loopedCallTotal = 0;
            for (var i = 0; i < 5; ++i)
                loopedCallTotal += InvokeWithLocal();
            AllocRecorder.enabled = false;
            var loopedCallAllocCount = AllocRecorder.sampleBlockCount;

            Assert.Greater(firstCallAllocCount, 0);
            Assert.AreEqual(firstCallAllocCount * 5, loopedCallAllocCount);

            Assert.AreEqual(0, firstCallTotal);
            Assert.AreEqual(0, loopedCallTotal);
        }

        int InvokeWithThis()
        {
            void WithThis(int v) { m_Field += v; }
            TestInvoke(WithThis);
            return m_Field;
        }

        [Test]
        public void WithThis_ShouldAllocEveryCall()
        {
            AllocRecorder.enabled = true;
            var firstCallTotal = InvokeWithThis();
            AllocRecorder.enabled = false;
            var firstCallAllocCount = AllocRecorder.sampleBlockCount;

            AllocRecorder.enabled = true;
            var loopedCallTotal = 0;
            for (var i = 0; i < 5; ++i)
                loopedCallTotal = InvokeWithThis();
            AllocRecorder.enabled = false;
            var loopedCallAllocCount = AllocRecorder.sampleBlockCount;

            Assert.Greater(firstCallAllocCount, 0);
            Assert.AreEqual(firstCallAllocCount * 5, loopedCallAllocCount);

            Assert.AreEqual(5, firstCallTotal);
            Assert.AreEqual(15, loopedCallTotal);
        }

        int InvokeWithStatic()
        {
            void WithStatic(int v) { s_Static += v; }
            TestInvoke(WithStatic);
            return s_Static;
        }

        [Test]
        [Ignore("Unstable")]
        public void WithStatic_ShouldAllocEveryCall()
        {
            AllocRecorder.enabled = true;
            var firstCallTotal = InvokeWithStatic();
            AllocRecorder.enabled = false;
            var firstCallAllocCount = AllocRecorder.sampleBlockCount;

            AllocRecorder.enabled = true;
            var loopedCallTotal = 0;
            for (var i = 0; i < 5; ++i)
                loopedCallTotal = InvokeWithStatic();
            AllocRecorder.enabled = false;
            var loopedCallAllocCount = AllocRecorder.sampleBlockCount;

            Assert.Greater(firstCallAllocCount, 0);
            Assert.AreEqual(firstCallAllocCount * 5, loopedCallAllocCount);

            Assert.AreEqual(6, firstCallTotal);
            Assert.AreEqual(16, loopedCallTotal);
        }

    }

    class ForEachLocalFunctionCachedMemoryTests : ForEachMemoryTestFixtureBase
    {
        TestDelegate m_EmptyDelegate;
        int InvokeEmpty()
        {
            void Empty(int v) { }
            TestInvoke(m_EmptyDelegate = m_EmptyDelegate ?? Empty);
            return 0;
        }

        [Test]
        public void Empty_ShouldAllocFirstCallOnly()
        {
            AllocRecorder.enabled = true;
            var firstCallTotal = InvokeEmpty();
            AllocRecorder.enabled = false;
            var firstCallAllocCount = AllocRecorder.sampleBlockCount;

            AllocRecorder.enabled = true;
            var loopedCallTotal = 0;
            for (var i = 0; i < 5; ++i)
                loopedCallTotal = InvokeEmpty();
            AllocRecorder.enabled = false;
            var loopedCallAllocCount = AllocRecorder.sampleBlockCount;

            Assert.Greater(firstCallAllocCount, 0);
            Assert.Zero(loopedCallAllocCount);

            Assert.AreEqual(0, firstCallTotal);
            Assert.AreEqual(0, loopedCallTotal);
        }

        TestDelegate m_WithThisDelegate;
        int InvokeWithThis()
        {
            void WithThis(int v) { m_Field += v; }
            TestInvoke(m_WithThisDelegate = m_WithThisDelegate ?? WithThis);
            return m_Field;
        }

        [Test]
        public void WithThis_ShouldAllocFirstCallOnly()
        {
            AllocRecorder.enabled = true;
            var firstCallTotal = InvokeWithThis();
            AllocRecorder.enabled = false;
            var firstCallAllocCount = AllocRecorder.sampleBlockCount;

            AllocRecorder.enabled = true;
            var loopedCallTotal = 0;
            for (var i = 0; i < 5; ++i)
                loopedCallTotal = InvokeWithThis();
            AllocRecorder.enabled = false;
            var loopedCallAllocCount = AllocRecorder.sampleBlockCount;

            Assert.Greater(firstCallAllocCount, 0);
            Assert.Zero(loopedCallAllocCount);

            Assert.AreEqual(5, firstCallTotal);
            Assert.AreEqual(15, loopedCallTotal);
        }

        TestDelegate m_WithStaticDelegate;
        int InvokeWithStatic()
        {
            void WithStatic(int v) { s_Static += v; }
            TestInvoke(m_WithStaticDelegate = m_WithStaticDelegate ?? WithStatic);
            return s_Static;
        }

        [Test]
        public void WithStatic_ShouldAllocFirstCallOnly()
        {
            AllocRecorder.enabled = true;
            var firstCallTotal = InvokeWithStatic();
            AllocRecorder.enabled = false;
            var firstCallAllocCount = AllocRecorder.sampleBlockCount;

            AllocRecorder.enabled = true;
            var loopedCallTotal = 0;
            for (var i = 0; i < 5; ++i)
                loopedCallTotal = InvokeWithStatic();
            AllocRecorder.enabled = false;
            var loopedCallAllocCount = AllocRecorder.sampleBlockCount;

            Assert.Greater(firstCallAllocCount, 0);
            Assert.Zero(loopedCallAllocCount);

            Assert.AreEqual(6, firstCallTotal);
            Assert.AreEqual(16, loopedCallTotal);
        }

    }

    class ForEachMethodMemoryTests : ForEachMemoryTestFixtureBase
    {
        void MethodEmpty(int v) { }

        int InvokeEmpty()
        {
            TestInvoke(MethodEmpty);
            return 0;
        }

        [Test]
        public void Empty_ShouldAllocEveryCall()
        {
            AllocRecorder.enabled = true;
            var firstCallTotal = InvokeEmpty();
            AllocRecorder.enabled = false;
            var firstCallAllocCount = AllocRecorder.sampleBlockCount;

            AllocRecorder.enabled = true;
            var loopedCallTotal = 0;
            for (var i = 0; i < 5; ++i)
                loopedCallTotal = InvokeEmpty();
            AllocRecorder.enabled = false;
            var loopedCallAllocCount = AllocRecorder.sampleBlockCount;

            Assert.Greater(firstCallAllocCount, 0);
            Assert.AreEqual(firstCallAllocCount * 5, loopedCallAllocCount);

            Assert.AreEqual(0, firstCallTotal);
            Assert.AreEqual(0, loopedCallTotal);
        }

        void MethodWithThis(int v) { m_Field += v; }

        int InvokeWithThis()
        {
            TestInvoke(MethodWithThis);
            return m_Field;
        }

        [Test]
        public void WithThis_ShouldAllocEveryCall()
        {
            AllocRecorder.enabled = true;
            var firstCallTotal = InvokeWithThis();
            AllocRecorder.enabled = false;
            var firstCallAllocCount = AllocRecorder.sampleBlockCount;

            AllocRecorder.enabled = true;
            var loopedCallTotal = 0;
            for (var i = 0; i < 5; ++i)
                loopedCallTotal = InvokeWithThis();
            AllocRecorder.enabled = false;
            var loopedCallAllocCount = AllocRecorder.sampleBlockCount;

            Assert.Greater(firstCallAllocCount, 0);
            Assert.AreEqual(firstCallAllocCount * 5, loopedCallAllocCount);

            Assert.AreEqual(5, firstCallTotal);
            Assert.AreEqual(15, loopedCallTotal);
        }

        void MethodWithStatic(int v) { s_Static += v; }

        int InvokeWithStatic()
        {
            TestInvoke(MethodWithStatic);
            return s_Static;
        }

        [Test]
        public void WithStatic_ShouldAllocEveryCall()
        {
            AllocRecorder.enabled = true;
            var firstCallTotal = InvokeWithStatic();
            AllocRecorder.enabled = false;
            var firstCallAllocCount = AllocRecorder.sampleBlockCount;

            AllocRecorder.enabled = true;
            var loopedCallTotal = 0;
            for (var i = 0; i < 5; ++i)
                loopedCallTotal = InvokeWithStatic();
            AllocRecorder.enabled = false;
            var loopedCallAllocCount = AllocRecorder.sampleBlockCount;

            Assert.Greater(firstCallAllocCount, 0);
            Assert.AreEqual(firstCallAllocCount * 5, loopedCallAllocCount);

            Assert.AreEqual(6, firstCallTotal);
            Assert.AreEqual(16, loopedCallTotal);
        }

    }

    class ForEachMethodCachedMemoryTests : ForEachMemoryTestFixtureBase
    {
        TestDelegate m_EmptyDelegate;
        void MethodEmpty(int v) { }

        int InvokeEmpty()
        {
            TestInvoke(m_EmptyDelegate = m_EmptyDelegate ?? MethodEmpty);
            return 0;
        }

        [Test]
        public void Empty_ShouldAllocFirstCallOnly()
        {
            AllocRecorder.enabled = true;
            var firstCallTotal = InvokeEmpty();
            AllocRecorder.enabled = false;
            var firstCallAllocCount = AllocRecorder.sampleBlockCount;

            AllocRecorder.enabled = true;
            var loopedCallTotal = 0;
            for (var i = 0; i < 5; ++i)
                loopedCallTotal = InvokeEmpty();
            AllocRecorder.enabled = false;
            var loopedCallAllocCount = AllocRecorder.sampleBlockCount;

            Assert.Greater(firstCallAllocCount, 0);
            Assert.Zero(loopedCallAllocCount);

            Assert.AreEqual(0, firstCallTotal);
            Assert.AreEqual(0, loopedCallTotal);
        }

        TestDelegate m_WithThisDelegate;
        void MethodWithThis(int v) { m_Field += v; }

        int InvokeWithThis()
        {
            TestInvoke(m_WithThisDelegate = m_WithThisDelegate ?? MethodWithThis);
            return m_Field;
        }

        [Test]
        public void WithThis_ShouldAllocFirstCallOnly()
        {
            AllocRecorder.enabled = true;
            var firstCallTotal = InvokeWithThis();
            AllocRecorder.enabled = false;
            var firstCallAllocCount = AllocRecorder.sampleBlockCount;

            AllocRecorder.enabled = true;
            var loopedCallTotal = 0;
            for (var i = 0; i < 5; ++i)
                loopedCallTotal = InvokeWithThis();
            AllocRecorder.enabled = false;
            var loopedCallAllocCount = AllocRecorder.sampleBlockCount;

            Assert.Greater(firstCallAllocCount, 0);
            Assert.Zero(loopedCallAllocCount);

            Assert.AreEqual(5, firstCallTotal);
            Assert.AreEqual(15, loopedCallTotal);
        }

        TestDelegate m_WithStaticDelegate;
        void MethodWithStatic(int v) { s_Static += v; }

        int InvokeWithStatic()
        {
            TestInvoke(m_WithStaticDelegate = m_WithStaticDelegate ?? MethodWithStatic);
            return s_Static;
        }

        [Test]
        public void WithStatic_ShouldAllocFirstCallOnly()
        {
            AllocRecorder.enabled = true;
            var firstCallTotal = InvokeWithStatic();
            AllocRecorder.enabled = false;
            var firstCallAllocCount = AllocRecorder.sampleBlockCount;

            AllocRecorder.enabled = true;
            var loopedCallTotal = 0;
            for (var i = 0; i < 5; ++i)
                loopedCallTotal = InvokeWithStatic();
            AllocRecorder.enabled = false;
            var loopedCallAllocCount = AllocRecorder.sampleBlockCount;

            Assert.Greater(firstCallAllocCount, 0);
            Assert.Zero(loopedCallAllocCount);

            Assert.AreEqual(6, firstCallTotal);
            Assert.AreEqual(16, loopedCallTotal);
        }

    }

    class ForEachStaticMethodMemoryTests : ForEachMemoryTestFixtureBase
    {
        static void StaticMethodEmpty(int v) { }

        int InvokeEmpty()
        {
            TestInvoke(StaticMethodEmpty);
            return 0;
        }

        [Test]
        public void Empty_ShouldAllocEveryCall()
        {
            AllocRecorder.enabled = true;
            var firstCallTotal = InvokeEmpty();
            AllocRecorder.enabled = false;
            var firstCallAllocCount = AllocRecorder.sampleBlockCount;

            AllocRecorder.enabled = true;
            var loopedCallTotal = 0;
            for (var i = 0; i < 5; ++i)
                loopedCallTotal = InvokeEmpty();
            AllocRecorder.enabled = false;
            var loopedCallAllocCount = AllocRecorder.sampleBlockCount;

            Assert.Greater(firstCallAllocCount, 0);
            Assert.AreEqual(firstCallAllocCount * 5, loopedCallAllocCount);

            Assert.AreEqual(0, firstCallTotal);
            Assert.AreEqual(0, loopedCallTotal);
        }

        static void StaticMethodWithStatic(int v) { s_Static += v; }

        int InvokeWithStatic()
        {
            TestInvoke(StaticMethodWithStatic);
            return s_Static;
        }

        [Test]
        public void WithStatic_ShouldAllocEveryCall()
        {
            AllocRecorder.enabled = true;
            var firstCallTotal = InvokeWithStatic();
            AllocRecorder.enabled = false;
            var firstCallAllocCount = AllocRecorder.sampleBlockCount;

            AllocRecorder.enabled = true;
            var loopedCallTotal = 0;
            for (var i = 0; i < 5; ++i)
                loopedCallTotal = InvokeWithStatic();
            AllocRecorder.enabled = false;
            var loopedCallAllocCount = AllocRecorder.sampleBlockCount;

            Assert.Greater(firstCallAllocCount, 0);
            Assert.AreEqual(firstCallAllocCount * 5, loopedCallAllocCount);

            Assert.AreEqual(6, firstCallTotal);
            Assert.AreEqual(16, loopedCallTotal);
        }

    }

    class ForEachStaticMethodCachedMemoryTests : ForEachMemoryTestFixtureBase
    {
        TestDelegate m_EmptyDelegate;
        static void StaticMethodEmpty(int v) { }

        int InvokeEmpty()
        {
            TestInvoke(m_EmptyDelegate = m_EmptyDelegate ?? StaticMethodEmpty);
            return 0;
        }

        [Test]
        public void Empty_ShouldAllocFirstCallOnly()
        {
            AllocRecorder.enabled = true;
            var firstCallTotal = InvokeEmpty();
            AllocRecorder.enabled = false;
            var firstCallAllocCount = AllocRecorder.sampleBlockCount;

            AllocRecorder.enabled = true;
            var loopedCallTotal = 0;
            for (var i = 0; i < 5; ++i)
                loopedCallTotal = InvokeEmpty();
            AllocRecorder.enabled = false;
            var loopedCallAllocCount = AllocRecorder.sampleBlockCount;

            Assert.Greater(firstCallAllocCount, 0);
            Assert.Zero(loopedCallAllocCount);

            Assert.AreEqual(0, firstCallTotal);
            Assert.AreEqual(0, loopedCallTotal);
        }

        TestDelegate m_WithStaticDelegate;
        static void StaticMethodWithStatic(int v) { s_Static += v; }

        int InvokeWithStatic()
        {
            TestInvoke(m_WithStaticDelegate = m_WithStaticDelegate ?? StaticMethodWithStatic);
            return s_Static;
        }

        [Test]
        public void WithStatic_ShouldAllocFirstCallOnly()
        {
            AllocRecorder.enabled = true;
            var firstCallTotal = InvokeWithStatic();
            AllocRecorder.enabled = false;
            var firstCallAllocCount = AllocRecorder.sampleBlockCount;

            AllocRecorder.enabled = true;
            var loopedCallTotal = 0;
            for (var i = 0; i < 5; ++i)
                loopedCallTotal = InvokeWithStatic();
            AllocRecorder.enabled = false;
            var loopedCallAllocCount = AllocRecorder.sampleBlockCount;

            Assert.Greater(firstCallAllocCount, 0);
            Assert.Zero(loopedCallAllocCount);

            Assert.AreEqual(6, firstCallTotal);
            Assert.AreEqual(16, loopedCallTotal);
        }

    }

}
#endif // !UNITY_DOTSPLAYER
